// Generated by CoffeeScript 1.6.3
var ret;

ret = linq(document).where(function(e) {
  return e.tagName.same("div");
}).where(function(e, i) {
  return e.id.same("2");
}).toArray();

console.log(ret);
