// Generated by CoffeeScript 1.6.3
var ret;

ret = document.getElementsByTagName("div").linq().where(function(e) {
  return e.tagName.toLowerCase() === "div";
});

console.log(ret);

ret = document.getElementsByTagName("div").linq().where(function(e, i) {
  return e.tagName.toLowerCase() === "div" && i < 2;
});

console.log(ret);
