// Generated by CoffeeScript 1.6.3
(function() {
  var Enumerable;
  this.linq = function(obj) {
    if (obj instanceof Enumerable) {
      return obj;
    }
    if (!(this instanceof Enumerable)) {
      return new Enumerable(obj);
    }
  };
  String.prototype.same = function(target) {
    return this.toLowerCase() === target.toLowerCase();
  };
  return Enumerable = (function() {
    function Enumerable(data) {
      this.data = data;
      if (this.data instanceof Document) {
        this.data = document.getElementsByTagName("*");
      }
    }

    Enumerable.prototype.where = function(func) {
      var i, ret, _i, _ref;
      ret = [];
      for (i = _i = 0, _ref = this.data.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        if (func(this.data[i], i)) {
          ret.push(this.data[i]);
        }
      }
      this.data = ret;
      return this;
    };

    Enumerable.prototype.select = function(func) {
      var i, ret, _i, _ref;
      ret = [];
      for (i = _i = 0, _ref = this.data.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        ret.push(func(this.data[i], i));
      }
      this.data = ret;
      return this;
    };

    Enumerable.prototype.selectMany = function(func) {};

    Enumerable.prototype.take = function(count) {
      this.data.splice(0, count);
      return this;
    };

    Enumerable.prototype.takeWhile = function(func) {
      var i, _i, _ref;
      i = 0;
      for (i = _i = 0, _ref = this.data.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        if (!func(this.data[i], i)) {
          break;
        }
      }
      this.data.splice(0, i);
      return this;
    };

    Enumerable.prototype.skip = function(count) {
      this.data.splice(count);
      return this;
    };

    Enumerable.prototype.skipWhile = function(func) {
      var i, _i, _ref;
      i = 0;
      for (i = _i = 0, _ref = this.data.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        if (func(this.data[i], i)) {
          break;
        }
      }
      this.data.splice(i);
      return this;
    };

    Enumerable.prototype.join = function() {};

    Enumerable.prototype.groupJoin = function() {};

    Enumerable.prototype.orderBy = function() {};

    Enumerable.prototype.orderByDescending = function() {};

    Enumerable.prototype.thenBy = function() {};

    Enumerable.prototype.thenByDescending = function() {};

    Enumerable.prototype.groupBy = function() {};

    Enumerable.prototype.concat = function(second) {
      var i, _i, _ref;
      for (i = _i = 0, _ref = second.lenght; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        this.data.push(second[i]);
      }
      return this;
    };

    Enumerable.prototype.distince = function(func) {};

    Enumerable.prototype.union = function(func) {};

    Enumerable.prototype.intersect = function(func) {};

    Enumerable.prototype.except = function() {};

    Enumerable.prototype.reverse = function() {};

    Enumerable.prototype.sequenceEqual = function() {};

    Enumerable.prototype.toArray = function() {
      return this.data;
    };

    Enumerable.prototype.defaultIfEmpty = function(source) {
      if (this.data.length === 0) {
        this.data = source;
      }
      return this;
    };

    Enumerable.prototype.ofType = function() {};

    Enumerable.prototype.cast = function() {};

    Enumerable.prototype.first = function(func) {
      if (func != null) {
        this.data = this.where(func).data;
      }
      return this.data[0];
    };

    Enumerable.prototype.firstOrDefault = function(func) {
      if (func != null) {
        this.data = this.where(func).data;
      }
      if (this.data.length === 0) {
        return null;
      }
      return this.data[0];
    };

    Enumerable.prototype.last = function(func) {
      if (func != null) {
        this.data = this.where(func).data;
      }
      return this.data.slice(-1)[0];
    };

    Enumerable.prototype.lastOrDefault = function(func) {
      if (func != null) {
        this.data = this.where(func).data;
      }
      if (this.data.length === 0) {
        return null;
      }
      return this.data.slice(-1)[0];
    };

    Enumerable.prototype.single = function(func) {
      return this.first(func).data;
    };

    Enumerable.prototype.singleOrDefault = function(func) {
      return this.firstOrDefault(func).data;
    };

    Enumerable.prototype.elementAt = function(index) {
      return this.data[index];
    };

    Enumerable.prototype.elementAtOrDefault = function(index) {
      if (this.data[index] != null) {
        return this.data[index];
      }
      return null;
    };

    Enumerable.prototype.range = function(start, count) {
      this.data.slice(start, count);
      return this;
    };

    Enumerable.prototype.any = function(func) {
      var current, i, _i, _ref;
      for (i = _i = 0, _ref = this.data.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        current = false;
        if (func != null) {
          current = !!this.data[i];
        } else {
          current = func(data[i]);
        }
        if (current) {
          return true;
        }
      }
      return false;
    };

    Enumerable.prototype.all = function(func) {
      var current, i, _i, _ref;
      for (i = _i = 0, _ref = this.data.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        current = false;
        if (func != null) {
          current = !!this.data[i];
        } else {
          current = func(data[i]);
        }
        if (!current) {
          return false;
        }
      }
      return true;
    };

    Enumerable.prototype.count = function(func) {
      if (func != null) {
        this.data = this.where(func).data;
      }
      return this.data.length;
    };

    return Enumerable;

  })();
})();
